title: 4137314 Portfolio
email: mattia.fait.science@gmail.com
description: Research & Development in Formal Systems
baseurl: "" 
url: "https://4137314.github.io"
markdown: kramdown
theme: minima # Opzionale, ma utile come fallback
exclude: [asset/cv/config, asset/cv/src] # Non compilare i sorgenti LaTeX come pagine
